import 'package:flutter/material.dart';

/* Text #010035
    Autogenerated by FlutLab FTF Generator
  */
class Generated010035Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''#010035''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.1009999593098958,
        fontSize: 30.0,
        fontFamily: 'Mark Pro',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 165, 165, 165),

        /* letterSpacing: -0.3333333432674408, */
      ),
    ));
  }
}
