import 'package:flutter/material.dart';
import 'package:flutterapp/ecommerceapp/generatedfilterswidget/generated/GeneratedVectorWidget78.dart';
import 'package:flutterapp/ecommerceapp/generatedfilterswidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/ecommerceapp/generatedfilterswidget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/ecommerceapp/generatedfilterswidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/ecommerceapp/generatedfilterswidget/generated/GeneratedGroup12Widget.dart';

/* Frame FILTERS
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFILTERSWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 951.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 951.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Container(
                                color: Color.fromARGB(255, 247, 247, 247),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 470.0,
                              height: 932.0,
                              child: GeneratedGroup10Widget(),
                            ),
                            Positioned(
                              left: 370.0,
                              top: 67.0,
                              right: null,
                              bottom: null,
                              width: 11.0,
                              height: 13.0,
                              child: GeneratedVectorWidget78(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 576.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 375.0,
                              child: GeneratedRectangle9Widget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 649.0,
                              right: null,
                              bottom: null,
                              width: 337.0,
                              height: 258.0,
                              child: GeneratedGroup15Widget(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 600.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 37.0,
                              child: GeneratedGroup12Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
