import 'package:flutter/material.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedDeliveryWidget.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedCheckoutWidget.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedFreeWidget.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedAddaddressWidget.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedVectorWidget92.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedConnectionsWidget4.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedTotalWidget.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedGroupWidget29.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedTimeWidget8.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedGroup16Widget1.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/Generated\$6000usWidget.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedGroup12Widget2.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedMyCartWidget.dart';
import 'package:flutterapp/ecommerceapp/generatedcartwidget/generated/GeneratedGroup24Widget.dart';

/* Frame CART
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCARTWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 951.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 951.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Container(
                                color: Color.fromARGB(255, 247, 247, 247),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 259.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 690.0,
                              child: GeneratedGroup16Widget1(),
                            ),
                            Positioned(
                              left: 313.0,
                              top: 26.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 16.0,
                              child: GeneratedConnectionsWidget4(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 56.0,
                              height: 23.0,
                              child: GeneratedTimeWidget8(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 79.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedGroup12Widget2(),
                            ),
                            Positioned(
                              left: 331.0,
                              top: 79.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedGroup22Widget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 104.0,
                              right: null,
                              bottom: null,
                              width: 14.0,
                              height: 7.0,
                              child: GeneratedVectorWidget92(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 851.0,
                              right: null,
                              bottom: null,
                              width: 326.0,
                              height: 54.0,
                              child: GeneratedRectangle10Widget2(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 865.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 30.0,
                              child: GeneratedCheckoutWidget(),
                            ),
                            Positioned(
                              left: 4.0,
                              top: 824.0,
                              right: null,
                              bottom: null,
                              width: 406.0,
                              height: 1.0,
                              child: GeneratedLine5Widget(),
                            ),
                            Positioned(
                              left: 4.0,
                              top: 733.0,
                              right: null,
                              bottom: null,
                              width: 406.0,
                              height: 2.0,
                              child: GeneratedLine6Widget(),
                            ),
                            Positioned(
                              left: 55.0,
                              top: 748.0,
                              right: null,
                              bottom: null,
                              width: 41.0,
                              height: 24.0,
                              child: GeneratedTotalWidget(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 748.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 21.0,
                              child: Generated$6000usWidget(),
                            ),
                            Positioned(
                              left: 55.0,
                              top: 779.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 24.0,
                              child: GeneratedDeliveryWidget(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 779.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 24.0,
                              child: GeneratedFreeWidget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 166.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 46.0,
                              child: GeneratedMyCartWidget(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 339.0,
                              right: null,
                              bottom: null,
                              width: 348.75,
                              height: 88.0,
                              child: GeneratedGroup23Widget(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 473.0,
                              right: null,
                              bottom: null,
                              width: 348.75,
                              height: 88.0,
                              child: GeneratedGroup24Widget(),
                            ),
                            Positioned(
                              left: 343.0,
                              top: 88.0,
                              right: null,
                              bottom: null,
                              width: 14.0,
                              height: 17.865007400512695,
                              child: GeneratedGroupWidget29(),
                            ),
                            Positioned(
                              left: 233.0,
                              top: 88.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 21.0,
                              child: GeneratedAddaddressWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
