import 'package:flutter/material.dart';

/* Text Mark Pro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMarkProWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Mark Pro''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.1009999593098958,
        fontSize: 60.0,
        fontFamily: 'Mark Pro',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: -0.3333333432674408, */
      ),
    ));
  }
}
