import 'package:flutter/material.dart';

/* Text Color palette
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedColorpaletteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Color palette''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.1009999593098958,
        fontSize: 30.0,
        fontFamily: 'Mark Pro',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: -0.3333333432674408, */
      ),
    ));
  }
}
