import 'package:flutter/material.dart';
import 'package:flutterapp/ecommerceapp/generatedsplashwidget/generated/GeneratedEcommerceConceptWidget.dart';
import 'package:flutterapp/ecommerceapp/generatedsplashwidget/generated/GeneratedEllipse2Widget.dart';

/* Frame splash
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 1, 0, 53),
                ),
              ),
              Positioned(
                left: 135.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 132.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 169.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 50.0,
                child: GeneratedEcommerceConceptWidget(),
              )
            ]),
      ),
    ));
  }
}
