import 'package:flutter/material.dart';
import 'package:flutterapp/ecommerceapp/generatedstyleguidewidget/generated/GeneratedEllipse3Widget3.dart';
import 'package:flutterapp/ecommerceapp/generatedstyleguidewidget/generated/GeneratedEllipse2Widget1.dart';

/* Frame styleguide
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStyleguideWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1078.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 700.0,
                      height: 1078.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 57.0,
                              top: 132.0,
                              right: null,
                              bottom: null,
                              width: 132.0,
                              height: 132.0,
                              child: GeneratedEllipse2Widget1(),
                            ),
                            Positioned(
                              left: 254.0,
                              top: 132.0,
                              right: null,
                              bottom: null,
                              width: 132.0,
                              height: 132.0,
                              child: GeneratedEllipse3Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
