import 'package:flutter/material.dart';
import 'package:flutterapp/ecommerceapp/generatedhome2widget/generated/GeneratedGroup7Widget2.dart';
import 'package:flutterapp/ecommerceapp/generatedhome2widget/generated/GeneratedGroup25Widget.dart';

/* Frame Home2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 247, 247, 247),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 18.0,
                right: null,
                bottom: null,
                width: 470.0,
                height: 1167.0,
                child: GeneratedGroup25Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 827.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 72.0,
                child: GeneratedGroup7Widget2(),
              )
            ]),
      ),
    ));
  }
}
