import 'package:flutter/material.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedGalaxyNote20UltraWidget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedMaskGroupWidget13.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedVectorWidget81.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedStar2Widget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedStar1Widget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedLayer68Widget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedConnectionsWidget3.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/Generated\$150000Widget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedStar5Widget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedTimeWidget6.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedDetailsWidget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedStar4Widget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedGroup12Widget1.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedMaskGroupWidget15.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedFeaturesWidget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedStar3Widget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedMaskGroupWidget14.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedAddtoCartWidget.dart';
import 'package:flutterapp/ecommerceapp/generateddetailswidget/generated/GeneratedShopWidget.dart';

/* Frame DETAILS
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDETAILSWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 973.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 951.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Container(
                                color: Color.fromARGB(255, 247, 247, 247),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 502.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 471.0,
                              child: GeneratedGroup16Widget(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 530.0,
                              right: null,
                              bottom: null,
                              width: 246.0,
                              height: 32.0,
                              child: GeneratedGalaxyNote20UltraWidget(),
                            ),
                            Positioned(
                              left: 313.0,
                              top: 26.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 16.0,
                              child: GeneratedConnectionsWidget3(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 56.0,
                              height: 23.0,
                              child: GeneratedTimeWidget6(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 79.0,
                              right: null,
                              bottom: null,
                              width: 337.0,
                              height: 37.0,
                              child: GeneratedGroup12Widget1(),
                            ),
                            Positioned(
                              left: 354.0,
                              top: 90.0,
                              right: null,
                              bottom: null,
                              width: 13.63845157623291,
                              height: 14.0,
                              child: GeneratedLayer68Widget(),
                            ),
                            Positioned(
                              left: 74.0,
                              top: 153.0,
                              right: null,
                              bottom: null,
                              width: 266.0,
                              height: 335.0,
                              child: GeneratedMaskGroupWidget13(),
                            ),
                            Positioned(
                              left: -175.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 279.0,
                              child: GeneratedRectangle18Widget(),
                            ),
                            Positioned(
                              left: 369.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 279.0,
                              child: GeneratedMaskGroupWidget14(),
                            ),
                            Positioned(
                              left: -178.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 279.0,
                              child: GeneratedMaskGroupWidget15(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 104.0,
                              right: null,
                              bottom: null,
                              width: 14.0,
                              height: 7.0,
                              child: GeneratedVectorWidget81(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 861.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 54.0,
                              child: GeneratedRectangle10Widget1(),
                            ),
                            Positioned(
                              left: 340.0,
                              top: 530.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 33.0,
                              child: GeneratedGroup19Widget(),
                            ),
                            Positioned(
                              left: 74.0,
                              top: 875.0,
                              right: null,
                              bottom: null,
                              width: 114.0,
                              height: 27.0,
                              child: GeneratedAddtoCartWidget(),
                            ),
                            Positioned(
                              left: 247.0,
                              top: 875.0,
                              right: null,
                              bottom: null,
                              width: 104.0,
                              height: 30.0,
                              child: Generated$150000Widget(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 617.0,
                              right: null,
                              bottom: null,
                              width: 54.0,
                              height: 30.0,
                              child: GeneratedShopWidget(),
                            ),
                            Positioned(
                              left: 163.0,
                              top: 617.0,
                              right: null,
                              bottom: null,
                              width: 72.0,
                              height: 30.0,
                              child: GeneratedDetailsWidget(),
                            ),
                            Positioned(
                              left: 290.0,
                              top: 617.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 30.0,
                              child: GeneratedFeaturesWidget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 650.0,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 3.0,
                              child: GeneratedLine7Widget(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 567.0,
                              right: null,
                              bottom: null,
                              width: 18.0,
                              height: 18.0,
                              child: GeneratedStar1Widget(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 567.0,
                              right: null,
                              bottom: null,
                              width: 18.0,
                              height: 18.0,
                              child: GeneratedStar2Widget(),
                            ),
                            Positioned(
                              left: 92.0,
                              top: 567.0,
                              right: null,
                              bottom: null,
                              width: 18.0,
                              height: 18.0,
                              child: GeneratedStar3Widget(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 567.0,
                              right: null,
                              bottom: null,
                              width: 18.0,
                              height: 18.0,
                              child: GeneratedStar4Widget(),
                            ),
                            Positioned(
                              left: 146.0,
                              top: 567.0,
                              right: null,
                              bottom: null,
                              width: 18.0,
                              height: 18.0,
                              child: GeneratedStar5Widget(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 683.0,
                              right: null,
                              bottom: null,
                              width: 344.0,
                              height: 47.0,
                              child: GeneratedGroup18Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
